# COMMENT_STRING #
# school_id # MASK_ME school_id
# school_secret # MASK_ME school_secret
totp_secret = ""
cert_file = ""
cert_password = ""

# Advanced settings
server_address = "stuvpn.fudan.edu.cn"
server_port = 443
disable_server_config = false
skip_domain_resource = false
disable_fdu_config = false
disable_fdu_dns = false
disable_multi_line = false
proxy_all = false
socks_bind = ":1080"
socks_user = ""
socks_passwd = ""
http_bind = ":1081"
shadowsocks_url = "" # "ss://aes-128-gcm:password@:1082"
dial_direct_proxy = "" # "http://127.0.0.1:7890" or "socks://127.0.0.1:7890"
tun_mode = false
add_route = false
dns_ttl = 3600
disable_keep_alive = false
fdu_dns_server = "202.120.224.26"
secondary_dns_server = "223.5.5.5"
dns_server_bind = ""
dns_hijack = false
debug_dump = false

# Port forwarding
port_forwarding = [
#    { network_type = "tcp", bind_address = "127.0.0.1:9898", remote_address = "10.10.98.98:80" },
#    { network_type = "tcp", bind_address = "127.0.0.1:9899", remote_address = "10.10.98.98:80" },
#    { network_type = "udp", bind_address = "127.0.0.1:1053", remote_address = "10.108.68.200:53" }
]

custom_dns = [
#    { host_name = "zb.fudan.edu.cn", ip = "10.108.68.200"},
#    { host_name = "mirrors.fducslg.com", ip = "10.176.52.2"}
]

custom_proxy_domain = [
#    "science.org",
#    "nature.com"
]
